In [ ]:
# Numpy - numerical python

# fast because of vectorization of cpu architenture


In [2]:
import numpy as np

In [3]:
# creating numpy arrays

# 1. From a Python list (most common)
my_list = [1, 2, 3, 4, 5]
arr_1d = np.array(my_list)
print(f"1D Array:\n {arr_1d}")

my_list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(my_list_2d)
print(f"\n2D Array (Matrix):\n {arr_2d}")

# 2. Using built-in creation functions
# 'arange' is like Python's 'range'
arr_range = np.arange(0, 10, 2)  # Start, Stop (exclusive), Step
print(f"\nArray from arange:\n {arr_range}")

# 'zeros' for an array of all zeros
arr_zeros = np.zeros((3, 4)) # Shape is (rows, cols)
print(f"\nZeros array (3x4):\n {arr_zeros}")

# 'ones' for an array of all ones
arr_ones = np.ones((2, 5), dtype=np.int16) # Can specify data type
print(f"\nOnes array (2x5):\n {arr_ones}")

# 'linspace' for evenly spaced numbers
# (Start, Stop (inclusive), Number of points)
arr_linspace = np.linspace(0, 10, 5)
print(f"\nLinspace array:\n {arr_linspace}")

# 3. Creating random data (super useful!)
# Random numbers from 0 to 1 (Uniform distribution)
arr_rand = np.random.rand(3, 3)
print(f"\nRandom array (uniform):\n {arr_rand}")

# Random numbers from a "Normal" (Gaussian) distribution
arr_randn = np.random.randn(3, 3)
print(f"\nRandom array (normal):\n {arr_randn}")

# Random integers
# (Low, High (exclusive), Size)
arr_randint = np.random.randint(1, 100, (2, 4))
print(f"\nRandom integer array:\n {arr_randint}")

1D Array:
 [1 2 3 4 5]

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array from arange:
 [0 2 4 6 8]

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array (2x5):
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Linspace array:
 [ 0.   2.5  5.   7.5 10. ]

Random array (uniform):
 [[0.68951115 0.97014538 0.09673251]
 [0.4443908  0.62838534 0.90685277]
 [0.9473151  0.27263773 0.7441068 ]]

Random array (normal):
 [[-2.05916565 -0.6892572  -0.97402435]
 [ 0.44472465  1.6999157  -0.74320831]
 [ 0.40797952  0.24122718 -1.38921213]]

Random integer array:
 [[24 77 87 81]
 [ 4 54  1 98]]


In [5]:
# array attributes

# Let's create a test array
data = np.random.randint(1, 20, (3, 4))
print(f"Our data:\n {data}")

# Get the shape (rows, columns)
print(f"\nShape: {data.shape}")

# Get the number of dimensions
print(f"Dimensions: {data.ndim}")

# Get the total number of elements
print(f"Size: {data.size}")

# Get the data type
print(f"Data Type: {data.dtype}")

Our data:
 [[18 19 19 17]
 [ 8 10 10  1]
 [ 9  9  1 16]]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data Type: int64


In [6]:
# array indexing and slicing

a = np.arange(10)
print(f"Array: {a}")

# Get a single element
print(f"Element at index 3: {a[3]}")

# Get a slice
print(f"Elements from index 2 to 5: {a[2:6]}")

# Get all elements from index 4 onwards
print(f"Elements from index 4: {a[4:]}")

# Get elements with a step
print(f"Every other element: {a[::2]}")

# Reverse the array
print(f"Reversed array: {a[::-1]}")

Array: [0 1 2 3 4 5 6 7 8 9]
Element at index 3: 3
Elements from index 2 to 5: [2 3 4 5]
Elements from index 4: [4 5 6 7 8 9]
Every other element: [0 2 4 6 8]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [7]:
# matrix indexing and slicing

# Create a 2D array
b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(f"Our 2D Array:\n {b}")

# Get a single element (Row 1, Column 2) -> (remember 0-indexing)
print(f"\nElement (1, 2): {b[1, 2]}") # This is 7

# Get an entire row (Row 0)
print(f"\nRow 0: {b[0, :]}")

# Get an entire column (Column 1)
print(f"\nColumn 1: {b[:, 1]}")

# Get a "slice" or sub-matrix
# Get the top-left 2x2 matrix
sub_matrix = b[0:2, 0:2] # Rows 0-1, Columns 0-1
print(f"\nTop-left 2x2:\n {sub_matrix}")

Our 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element (1, 2): 7

Row 0: [1 2 3 4]

Column 1: [ 2  6 10]

Top-left 2x2:
 [[1 2]
 [5 6]]


In [8]:
# making partitions of arrays or matrices without copying data doesn't create a new array but a view of original array, 
# so changes to the view affect the original array.

# 1. The 'View' (default behavior)
a = np.arange(5)
print(f"Original array: {a}")

# Create a slice (a view)
a_view = a[1:4]
print(f"View: {a_view}")

# Now, modify the view
a_view[0] = 99
print(f"Modified view: {a_view}")
print(f"!!! Original array is CHANGED: {a}")

# 2. How to make a 'Copy'
b = np.arange(5)
print(f"\nOriginal array 'b': {b}")

# Explicitly create a copy
b_copy = b[1:4].copy()
print(f"Copy: {b_copy}")

# Modify the copy
b_copy[0] = 77
print(f"Modified copy: {b_copy}")
print(f"Original 'b' is UNCHANGED: {b}")

Original array: [0 1 2 3 4]
View: [1 2 3]
Modified view: [99  2  3]
!!! Original array is CHANGED: [ 0 99  2  3  4]

Original array 'b': [0 1 2 3 4]
Copy: [1 2 3]
Modified copy: [77  2  3]
Original 'b' is UNCHANGED: [0 1 2 3 4]


In [9]:
# vectorized operations - element-wise operations

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# No loops needed!
print(f"a + b = {a + b}")
print(f"a * b = {a * b}")
print(f"a * 10 = {a * 10}")
print(f"a ** 2 = {a ** 2}")

a + b = [11 22 33]
a * b = [10 40 90]
a * 10 = [10 20 30]
a ** 2 = [1 4 9]


In [10]:
# universal functions (ufuncs)

data = np.array([1, 4, 9, 16])

# Square root
print(f"sqrt: {np.sqrt(data)}")

# Exponential
print(f"exp: {np.exp(data)}")

# Sine
print(f"sin: {np.sin(data)}")

sqrt: [1. 2. 3. 4.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [ ]:
# axis parameter in numpy functions

# axis=0: Perform the operation down the columns.
# axis=1: Perform the operation across the rows.

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(f"Data:\n {data}")

# Sum of all elements
print(f"\nTotal sum: {data.sum()}")

# Sum *down* the columns (axis=0)
print(f"\nSum of columns: {data.sum(axis=0)}")

# Mean *across* the rows (axis=1)
print(f"\nMean of rows: {data.mean(axis=1)}")

# Max of each column
print(f"\nMax of columns: {data.max(axis=0)}")

Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Total sum: 45

Sum of columns: [12 15 18]

Mean of rows: [2. 5. 8.]

Max of columns: [7 8 9]


In [ ]:
# braodcasting - working with arrays of different shapes

# If two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
# If the shape of two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
# If in any dimension the sizes disagree and neither is equal to 1, an error is raised

# Example 1: Array and a Scalar (Easiest case)
a = np.arange(5)
print(f"Array: {a}")
print(f"Array + 10: {a + 10}") # 10 is "broadcast" to [10, 10, 10, 10, 10]

# Example 2: 2D array and 1D array
matrix = np.ones((3, 3)) # 3x3 array of 1s
row = np.array([1, 2, 3]) # 1x3 array
print(f"\nMatrix:\n {matrix}")
print(f"Row: {row}")

# The row [1, 2, 3] is "broadcast" (stretched) to all 3 rows
print(f"\nMatrix + Row:\n {matrix + row}")

# Example 3: 2D array and 1D *column*
# We need to reshape the column to be (3, 1)
col = np.array([[10], [20], [30]])
print(f"\nColumn:\n {col}")

# The column is broadcast (stretched) to all 3 columns
print(f"\nMatrix + Column:\n {matrix + col}")

# for those without any dimension one and uneven shapes, no result
test1=np.array([[1,2,3],[5,6,7],[9,10,11]])
test2=np.array([[10,20],[30,40],[50,60]])
print(f"matrix + matrix:\n {test1 + test2}")

Array: [0 1 2 3 4]
Array + 10: [10 11 12 13 14]

Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Row: [1 2 3]

Matrix + Row:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]

Column:
 [[10]
 [20]
 [30]]

Matrix + Column:
 [[11. 11. 11.]
 [21. 21. 21.]
 [31. 31. 31.]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [18]:
# boolean indexing - filtering data based on conditions / masking

data = np.random.randn(5, 4)
print(f"Data:\n {data}")

# Create a boolean mask
# Find all values greater than 0
mask = data > 0
print(f"\nMask:\n {mask}")

# Use the mask to select ONLY the positive values
print(f"\nPositive values: {data[mask]}")

# You can also use it to set values
# Set all negative numbers to 0
data[data < 0] = 0
print(f"\nData with negatives zeroed out:\n {data}")

# Example: Get all rows where the value in column 2 is positive
data_2 = np.random.randn(8, 4)
print(f"\nNew data:\n {data_2}")

# 1. Get the boolean mask for column 2
mask_col_2 = data_2[:, 2] > 0
print(f"Mask for col 2: {mask_col_2}")

# 2. Use that mask to select the *rows*
print(f"\nRows where col 2 is positive:\n {data_2[mask_col_2]}")

Data:
 [[-0.75573317 -0.14548913 -2.17673759  0.01133771]
 [ 0.39382601 -0.9117017  -0.21747741 -0.45917479]
 [ 0.38204291 -0.53990416 -0.07974177 -0.58254533]
 [ 0.60975373 -0.66066541 -1.0900421  -2.38779527]
 [ 0.88083146  0.75143017 -2.01257526 -0.27926057]]

Mask:
 [[False False False  True]
 [ True False False False]
 [ True False False False]
 [ True False False False]
 [ True  True False False]]

Positive values: [0.01133771 0.39382601 0.38204291 0.60975373 0.88083146 0.75143017]

Data with negatives zeroed out:
 [[0.         0.         0.         0.01133771]
 [0.39382601 0.         0.         0.        ]
 [0.38204291 0.         0.         0.        ]
 [0.60975373 0.         0.         0.        ]
 [0.88083146 0.75143017 0.         0.        ]]

New data:
 [[-6.06840011e-01 -6.85703028e-04  9.24985589e-01 -1.17383608e+00]
 [-1.06158627e+00  1.49632358e+00 -5.63716565e-01 -1.45455175e+00]
 [-2.74495831e+00  8.82343731e-01 -1.46554328e+00  2.39801673e-02]
 [ 6.40449766e-01  1.083

In [19]:
# integer arrays - fancy indexing

arr = np.arange(20, 30) # [20, 21, ..., 29]
print(f"Array: {arr}")

# Select elements at specific indices
indices = [1, 4, 8]
print(f"Fancy selection: {arr[indices]}")

# You can also use it for 2D arrays
matrix = np.arange(9).reshape(3, 3)
print(f"\nMatrix:\n {matrix}")

# Select rows 0 and 2
print(f"\nRows 0 & 2:\n {matrix[[0, 2]]}")

Array: [20 21 22 23 24 25 26 27 28 29]
Fancy selection: [21 24 28]

Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Rows 0 & 2:
 [[0 1 2]
 [6 7 8]]


In [20]:
# advanced indexing

# You can also use it to set values
# Set all negative numbers to 0
data[data < 0] = 0
print(f"\nData with negatives zeroed out:\n {data}")

# Combining masks
data2 = np.random.randint(0, 20, (5, 5))
print(f"\nNew data:\n {data2}")

# Use & (AND) and | (OR)
# NOT 'and' or 'or'
mask_combined = (data2 > 5) & (data2 < 15)
print(f"\nCombined Mask (5 < x < 15):\n {mask_combined}")

# Set values matching the mask to -1
data2[mask_combined] = -1
print(f"\nData with mask applied:\n {data2}")


Data with negatives zeroed out:
 [[0.         0.         0.         0.01133771]
 [0.39382601 0.         0.         0.        ]
 [0.38204291 0.         0.         0.        ]
 [0.60975373 0.         0.         0.        ]
 [0.88083146 0.75143017 0.         0.        ]]

New data:
 [[ 1  8 15 14  3]
 [ 9 16 18  9  3]
 [16  2  3 13  0]
 [ 5 16  7  5 16]
 [ 2 15 14  5  9]]

Combined Mask (5 < x < 15):
 [[False  True False  True False]
 [ True False False  True False]
 [False False False  True False]
 [False False  True False False]
 [False False  True False  True]]

Data with mask applied:
 [[ 1 -1 15 -1  3]
 [-1 16 18 -1  3]
 [16  2  3 -1  0]
 [ 5 16 -1  5 16]
 [ 2 15 -1  5 -1]]


In [ ]:
# array manipulation - reshaping

a = np.arange(12)
print(f"Original (size={a.size}): {a}")

# Reshape to 3 rows, 4 columns
b = a.reshape(3, 4)
print(f"\nReshaped (3x4):\n {b}")

# Reshape to 4 rows, 3 columns
c = a.reshape(4, 3)
print(f"\nReshaped (4x3):\n {c}")

# You can use -1 to have NumPy automatically calculate one dimension
d = a.reshape(6, -1) # Will be (6, 2)
print(f"\nReshaped (6, -1) -> (6, 2):\n {d}")

Original (size=12): [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped (6, -1) -> (6, 2):
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [22]:
# array manipulation - stacking

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stack vertically (along axis=0)
v_stack = np.vstack((a, b))
# Also: np.concatenate([a, b], axis=0)
print(f"Vertical Stack:\n {v_stack}")

# Stack horizontally (along axis=1)
h_stack = np.hstack((a, b))
# Also: np.concatenate([a, b], axis=1)
print(f"\nHorizontal Stack:\n {h_stack}")

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [23]:
# array manipulation - splitting

data = np.arange(12).reshape(6, 2)
print(f"Data:\n {data}")

# Split into 3 equal arrays vertically
v_split = np.vsplit(data, 3)
print(f"\nVertical Split:\n {v_split[0]}\n...\n{v_split[1]}\n...\n{v_split[2]}")

Data:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

Vertical Split:
 [[0 1]
 [2 3]]
...
[[4 5]
 [6 7]]
...
[[ 8  9]
 [10 11]]
