# Pandas and Numpy

In [1]:
import numpy as np
import pandas as pd

## Problem 1

#### Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
#### Expected Output:
#### Array1: [ 0 10 20 40 60]
#### Array2: [0, 40]
#### Compare each element of array1 and array2
#### Output: [ True False False True False]

In [61]:
array1= np.array([0,10,20,40,60])
array2= np.array([0,40])
array3=np.isin(array1,array2)
print(array3)

[ True False False  True False]


## Problem 2
#### Write a NumPy program to get the unique elements of an array
#### Expected Output:
#### Original array:
#### [10 10 20 20 30 30]
#### Unique elements of the above array:
#### [10 20 30]
#### Original array:
#### [[1 1]
#### [2 3]]
#### Unique elements of the above array:
#### [1 2 3]

In [17]:
array1= np.array([0,10,10,10,20,40,60])
print(np.unique(array1))
array2=[[1,1],[2,3]]
print(np.unique(array2))

[ 0 10 20 40 60]
[1 2 3]


## Problem 3
#### Write a NumPy program to sort an along the first, last axis of an array.
#### Sample array: [[2,5],[4,4]]
#### Expected Output:
#### Original array:
#### [[4 6]
#### [2 1]]
#### Sort along the first axis:
#### [[2 1]
#### [4 6]]
#### Sort along the last axis:
#### [[1 2]
#### [4 6]]

In [25]:
array=[[4,6],[2,1]]
print(np.sort(array,axis=0))
print(np.sort(array,axis=1))

[[2 1]
 [4 6]]
[[4 6]
 [1 2]]


## Problem 4
#### Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
#### Sample Output:
#### Original array:
#### [10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
#### [4,1,7,3]

In [15]:
array=[10,20,30,40,50,10,10,20,30,30,30,30,50,40]
print(array.count(40))

2


## Problem 5
#### Write a NumPy program to remove nan values from a given array.
#### Sample Output:
#### Original array:
#### [200. 300. nan nan nan 700.]
#### After removing nan values:
#### [200. 300. 700.]

In [ ]:

array=np.array([1,2,np.nan,4,5])
arr=array[~np.isnan(array)]
print(arr)

[1. 2. 4. 5.]


## Problem 6
#### Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
#### Sample Output:
#### 50th percentile (median):
#### 3.0
#### 40th percentile:
#### 2.6
#### 90th percentile:
#### 4.6

In [40]:
array=np.array([1,2,3,4,5])
print(np.percentile(array,50))
print(np.percentile(array,40))
print(np.percentile(array,90))

3.0
2.6
4.6


## Problem 7
#### Write a NumPy program to find indices of elements equal to zero in a NumPy array.
#### Sample Output:
#### Original array:
#### [1 0 2 0 3 0 4 5 6 7 8]
#### Indices of elements equal to zero of the said array:
#### [1 3 5]

In [ ]:
array1= np.array([1,0,10,0,40,0,60,80])
array2= np.array([0])
array3=np.where(np.isin(array1,array2))
print(array3)

(array([1, 3, 5]),)


## Problem 8

#### Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.
#### Sample Output:
#### Original array:
#### [-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
#### Round elements of the array to the nearest integer:
#### [1. 2. 2. 0. 2. 2. 2.]

## Problem 9
#### Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
#### Sample output:
#### Original array:
#### [1 3 5 7 0]
#### Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
#### [ 0 0 2 2 2 -7 200]
#### Note:  difference between neighboring elements means: $out[i] = a[i+1] - a[i]$

In [60]:
ans=[]
ans.append(0)
ans.append(0)
arr=np.array([1,3,5,7,0])
for i in range(0,4):
    ans.append(arr[i+1]-arr[i])
ans.append(200)
print(ans)

[0, 0, np.int64(2), np.int64(2), np.int64(2), np.int64(-7), 200]


## Problem 10
#### Write a NumPy program to get the indices of the sorted elements of a given array.
#### Expected Output:
#### Original array:
#### [1023 5202 6230 1671 1682 5241 4532]
#### Indices of the sorted elements of a given array:
#### [0 3 4 6 1 5 2]

In [ ]:
array=np.array([3,1,2,4,5])
indices=np.argsort(array)
print(indices)

[1 2 0 3 4]


## Problem 11
#### Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
#### Sample output:
#### Original array:
#### [ 70 50 20 30 -11 60 50 40]
#### After partitioning on 4 the position:
#### [-11 30 20 40 50 50 60 70]

## Problem 12
#### Compute the euclidean distance between two arrays a and b.

#### Input:
#### [1,2,3,4,5]
#### [4,5,6,7,8]
#### Euclidean distance is: 6.7082

6.708203932499369


## Problem 13
#### Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

#### Input:

#### array([1, 3, 7, 1, 2, 6, 0, 1])

#### Desired Output:

#### array( [2, 5])
#### where, 2 and 5 are the positions of peak values 7 and 6.

## Problem 14
#### Find the index of nth repetition of number i .
#### Inputs
#### array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
#### n = 5 (from user)
#### i = 1 (from user)
#### Output
#### 8

#  <span style="color:brown">Problem 15

## <span style="color:blue">Problem statment

The content, tone, and format of job bulletins can influence the quality of the applicant pool. Overly-specific job requirements may discourage diversity. The Los Angeles Mayor’s Office wants to reimagine the city’s job bulletins by using text analysis to identify needed improvements, in order to achive this use the daatset in the relative diretcotry ./Datasets/la_jobs.csv, and this is the decomentation for the useful columns you should use:

- FILE_NAME: The bulletins file name.
- JOB_CLASS_TITLE: Job title.
- JOB_CLASS_NO: Job number.
- JOB_DUTIES: The duties of this job.
- EDUCATION_YEARS: Number of education yeras needed to apply for this job.
- SCHOOL_TYPE: The type of school you need to study in.
- EDUCATION_MAJOR: The eductaion major you study in this school.
- EXPERIENCE_LENGTH: The number of experience years needed to apply for this job .
- FULL_TIME_PART_TIME: If the job is full time or part time or both.
- EXP_JOB_CLASS_TITLE: The title of the job you must have experience in before applying in this job.
- COURSE_COUNT: Number of courses needed to apply for this job.
- COURSE_LENGTH: The course length in years or months.
- COURSE_SUBJECT: The course subject tha is needed to be accepted in this job.
- DRIVERS_LICENSE_REQ: Is driver license required or not for this job.
- EXAM_TYPE: Type of exams neededin the hiring process.
- ENTRY_SALARY: Salary range in this job.
- OPEN_DATE: Date at it the job bulliten got open.
- REQUIREMENT_SET_TEXT: The requirments set need for this job in points.

    

#### The goal is to answer the following questions
 

### <span style="color:brown">Q1:

A non-experienced job seeker wants to know what is the best job for him?

### <span style="color:brown">Q2:

A concerned parents contacts you to tell them if there is a spicific school type that would guaranteed for their child a good future if you can tell, and which is it ?

### <span style="color:brown">Q3:

What the best time in the year to be ready for a job applying in any experience level?

### <span style="color:brown">Q4:

Is experience more important than educational level?

### <span style="color:brown">Q5:

Which fresh grade job that will guarantee many job offers in the future for him?

### <span style="color:brown">Q6:

"The City of Los Angeles does not discriminate on the basis of race, religion, national origin, sex, age, marital status, sexual orientation, gender identity, gender expression, disability, creed, color, ancestry, medical condition (cancer), or Acquired Immune Deficiency Syndrome.

AN EQUAL EMPLOYMENT OPPORTUNITY EMPLOYER 
"

The above statment is qouted from one of the job descriptions.

Based on the jobs requirments column above do you think that LA governate may bais a little for men over women or the applicant marital status for example may effect his chance to gain the job?