# 1. MLP  + Activation Functions

Feed Forward Propagation and Backpropagation

Pytorch PowerYe

### Libraries

In [16]:
!pip install torchinfo

In [10]:
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np


### 1. MLP(Multi-layer Percepton)

In [11]:
# Xor Data

In [12]:
X = torch.tensor([
    [0.,0.],
    [0.,1.],
    [1.,0.],
    [1.,1.]
])
y = torch.tensor([[0.],[1.],[1.],[0.]])

In [13]:
X.shape

torch.Size([4, 2])

In [18]:
y.shape

torch.Size([4, 1])

In [14]:
X.dtype

torch.float32

In [15]:
# Model
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,10)
        self.fc2 = nn.Linear(10,5)
        self.fc3 = nn.Linear(5,1)
        #self.dropout1 = nn.Dropout(p=0.2)
    def forward(self,x):
        x = torch.relu(self.fc1(x))
        #x = self.fc1(x)
        x = torch.relu(self.fc2(x))
        #x = self.dropout1(x)

        x = self.fc3(x)
        return x

In [17]:
model = MLP()
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
MLP                                      --
├─Linear: 1-1                            30
├─Linear: 1-2                            55
├─Linear: 1-3                            6
Total params: 91
Trainable params: 91
Non-trainable params: 0

In [ ]:
for name, param in model.named_parameters():
    print(name, param)

fc1.weight Parameter containing:
tensor([[ 0.1844,  0.1126],
        [ 0.5608, -0.6710],
        [ 0.5574,  0.4888],
        [ 0.1176,  0.0662],
        [ 0.3487,  0.1159],
        [ 0.6725, -0.5871],
        [ 0.4786,  0.6285],
        [ 0.4556,  0.0469],
        [ 0.3481,  0.0778],
        [ 0.0335, -0.3867]], requires_grad=True)
fc1.bias Parameter containing:
tensor([ 0.0181,  0.4487,  0.4134, -0.4448, -0.4183,  0.2794, -0.1890, -0.3039,
        -0.1861, -0.7006], requires_grad=True)
fc2.weight Parameter containing:
tensor([[-0.2958,  0.2566,  0.2820, -0.2638,  0.2164, -0.0087,  0.2081,  0.1337,
         -0.1649,  0.1238],
        [-0.0149,  0.2777,  0.2081, -0.2362,  0.1871, -0.1645, -0.2116, -0.1892,
          0.0331,  0.0779],
        [-0.1009, -0.2833, -0.0153,  0.0353,  0.0392, -0.0511, -0.2099,  0.0633,
          0.3016, -0.0695],
        [-0.2920, -0.2676, -0.2872,  0.0589,  0.1784,  0.2212, -0.1517, -0.2783,
          0.1515, -0.1075],
        [-0.1038,  0.1679,  0.2083, -0.

In [19]:
# Train
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

for epoch in range(2000):
    optimizer.zero_grad()
    out = model(X)
    #print(out)
    loss = criterion(out,y)
    loss.backward()
    optimizer.step()

    if (epoch+1)%400==0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


Epoch 400, Loss: 0.2034
Epoch 800, Loss: 0.0102
Epoch 1200, Loss: 0.0036
Epoch 1600, Loss: 0.0020
Epoch 2000, Loss: 0.0013


In [23]:

x = torch.tensor(2.0, requires_grad=True)
y1 = x * x + 3*x + 5
y1.backward()

print(x.grad)


tensor(7.)


In [21]:
# Test
with torch.no_grad():
    probs = torch.sigmoid(model(X))
    preds = (probs>0.5).float()

print("Probabilities:\n", probs)
print("Classes:\n", preds)

Probabilities:
 tensor([[2.2698e-03],
        [9.9846e-01],
        [9.9945e-01],
        [9.2732e-04]])
Classes:
 tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [ ]:
#updated

In [ ]:
for name, param in model.named_parameters():
    print(f"{name}:\n{param.detach().numpy()}\n")

fc1.weight:
[[ 0.37823352 -0.10621942]
 [ 1.8174701  -1.1465299 ]
 [-0.15899798  1.5443915 ]
 [ 0.11755824  0.06621253]
 [ 0.33306068  0.10025876]
 [ 1.3443713  -0.7454019 ]
 [ 0.5121128   0.5121293 ]
 [ 0.5392854   0.57723194]
 [ 1.234381   -0.92183363]
 [ 0.03351003 -0.38669994]]

fc1.bias:
[-2.7395656e-05  1.1465392e+00  1.3782421e+00 -4.4480056e-01
 -4.3400359e-01  7.4531686e-01 -5.1215273e-01 -5.3932846e-01
 -4.0438666e-05 -7.0059061e-01]

fc2.weight:
[[-0.39291534  0.45973653  0.9660708  -0.2637994   0.21777876  0.07670083
   0.46788952  0.41953146 -0.7165813   0.12384546]
 [-0.02320135  0.21412359  0.12366815 -0.23618603  0.18711343 -0.21518384
  -0.21975316 -0.19218235  0.01737973  0.07791945]
 [-0.19269781 -1.796038    1.4783394   0.03528273  0.0358743  -1.2407696
  -0.10180788 -0.13366696  0.2640647  -0.0694914 ]
 [-0.29199132 -0.26761603 -0.28717113  0.05888191  0.17838722  0.22124818
  -0.15169026 -0.27831388  0.15145016 -0.10754456]
 [ 0.15508024  1.3105642  -0.80144674 -0

# Task Lab

In [ ]:
# Data

In [ ]:
# Combined dataset: bikes for short distances, cars for longer ones
distances = torch.tensor([
    [1.0], [1.5], [2.0], [2.5], [3.0], [3.5], [4.0], [4.5], [5.0], [5.5],
    [6.0], [6.5], [7.0], [7.5], [8.0], [8.5], [9.0], [9.5], [10.0], [10.5],
    [11.0], [11.5], [12.0], [12.5], [13.0], [13.5], [14.0], [14.5], [15.0], [15.5],
    [16.0], [16.5], [17.0], [17.5], [18.0], [18.5], [19.0], [19.5], [20.0]
], dtype=torch.float32)

# Corresponding delivery times in minutes
times = torch.tensor([
    [6.96], [9.67], [12.11], [14.56], [16.77], [21.7], [26.52], [32.47], [37.15], [42.35],
    [46.1], [52.98], [57.76], [61.29], [66.15], [67.63], [69.45], [71.57], [72.8], [73.88],
    [76.34], [76.38], [78.34], [80.07], [81.86], [84.45], [83.98], [86.55], [88.33], [86.83],
    [89.24], [88.11], [88.16], [91.77], [92.27], [92.13], [90.73], [90.39], [92.98]
], dtype=torch.float32)

### ###  Normalizing the Data

Before building your model, you will apply a quick data preparation step called **normalization**. This is a standard technique that makes the training process more stable and effective by adjusting the scale of the data. This adjustment helps prevent large distance values from dominating the learning process and keeps gradients stable during training. You will explore this topic in greater detail in a later module.

* You will calculate the mean and standard deviation for the `distances` and `times` tensors.
* You will then apply standardization to each tensor using its respective mean and standard deviation, which creates new normalized tensors named `distances_norm` and `times_norm`.
* This specific technique is called **standardization** (or z-score normalization), which converts the original data from `1.0 to 20.0 miles` and approximately `7 to 93 minutes` into a new, normalized scale.

In [ ]:
# Calculate the mean and standard deviation for the 'distances' tensor
distances_mean = distances.mean()
distances_std = distances.std()

# Calculate the mean and standard deviation for the 'times' tensor
times_mean = times.mean()
times_std = times.std()

# Apply standardization to the distances.
distances_norm = (distances - distances_mean) / distances_std

# Apply standardization to the times.
times_norm = (times - times_mean) / times_std

In [ ]:
## Building the Non-Linear Model
#Build model with 4 layers
#Code here

In [ ]:
# Define the loss function and optimizer
# code

In [ ]:
#loss_function = ()MSELoss
#optimizer = optim.------(model_2.parameters(), lr=)#SGD,Adam

In [ ]:
'''
from IPython.display import clear_output
import time
def plot_training_progress(epoch, loss, model_2, distances_norm, times_norm):
    """
    Plots the training progress of a model on normalized data,
    showing the current fit at each epoch.

    Args:
        epoch: The current training epoch number.
        loss: The loss value at the current epoch.
        model: The model being trained.
        distances_norm: The normalized input data.
        times_norm: The normalized target data.
    """
    # Clear the previous plot from the output cell
    clear_output(wait=True)

    # Make predictions using the current state of the model
    predicted_norm = model_2(distances_norm)

    # Convert tensors to NumPy arrays for plotting
    x_plot = distances_norm.numpy()
    y_plot = times_norm.numpy()

    # Detach predictions from the computation graph and convert to NumPy
    y_pred_plot = predicted_norm.detach().numpy()

    # Sort the data based on distance to ensure a smooth line plot
    sorted_indices = x_plot.argsort(axis=0).flatten()

    # Create a new figure for the plot
    plt.figure(figsize=(8, 6))

    # Plot the original normalized data points
    plt.plot(x_plot, y_plot, color='orange', marker='o', linestyle='none', label='Actual Normalized Data')

    # Plot the model's predictions as a line
    plt.plot(x_plot[sorted_indices], y_pred_plot[sorted_indices], color='green', label='Model Predictions')

    # Set the title of the plot, including the current epoch
    plt.title(f'Epoch: {epoch + 1} | Normalized Training Progress')
    # Set the x-axis label
    plt.xlabel('Normalized Distance')
    # Set the y-axis label
    plt.ylabel('Normalized Time')
    # Display the legend
    plt.legend()
    # Add a grid to the plot
    plt.grid(True)
    # Show the plot
    plt.show()

    # Pause briefly to allow the plot to be rendered
    time.sleep(0.05)
'''

'\nfrom IPython.display import clear_output\nimport time\ndef plot_training_progress(epoch, loss, model_2, distances_norm, times_norm):\n    """\n    Plots the training progress of a model on normalized data,\n    showing the current fit at each epoch.\n\n    Args:\n        epoch: The current training epoch number.\n        loss: The loss value at the current epoch.\n        model: The model being trained.\n        distances_norm: The normalized input data.\n        times_norm: The normalized target data.\n    """\n    # Clear the previous plot from the output cell\n    clear_output(wait=True)\n\n    # Make predictions using the current state of the model\n    predicted_norm = model_2(distances_norm)\n\n    # Convert tensors to NumPy arrays for plotting\n    x_plot = distances_norm.numpy()\n    y_plot = times_norm.numpy()\n    \n    # Detach predictions from the computation graph and convert to NumPy\n    y_pred_plot = predicted_norm.detach().numpy()\n\n    # Sort the data based on dis

In [ ]:
'''
# Training loop
for epoch in range(3000):
    # Reset the optimizer's gradients
    optimizer.zero_grad()
    # Make predictions (forward pass)
    outputs = model_2(----------)
    # Calculate the loss
    loss = loss_function(-----, -------)
    # Calculate adjustments (backward pass)
   #code
    # Update the model's parameters
    #code

    # Create a live plot every 50 epochs
    if (epoch + 1) % 50 == 0:
        plot_training_progress(
            epoch=epoch,
            loss=loss,
            model_2=model_2,
            distances_norm=distances_norm,
            times_norm=times_norm
        )

print("\nTraining Complete.")
print(f"\nFinal Loss: {loss.item()}")
'''

'\n# Training loop\nfor epoch in range(3000):\n    # Reset the optimizer\'s gradients\n    optimizer.zero_grad()\n    # Make predictions (forward pass)\n    outputs = model_2(----------)\n    # Calculate the loss\n    loss = loss_function(-----, -------)\n    # Calculate adjustments (backward pass)\n   #code \n    # Update the model\'s parameters\n    #code\n\n    # Create a live plot every 50 epochs\n    if (epoch + 1) % 50 == 0:\n        plot_training_progress(\n            epoch=epoch,\n            loss=loss,\n            model_2=model_2,\n            distances_norm=distances_norm,\n            times_norm=times_norm\n        )\n\nprint("\nTraining Complete.")\nprint(f"\nFinal Loss: {loss.item()}")\n'

## Making a Prediction

With your fully trained non-linear model, you can now use it to make a prediction for a new delivery. The process is slightly different now because your model was trained on *normalized* data.

* First, you will take the new input distance and **normalize** it using the same mean and standard deviation from your training data. This step is CRITICAL: your model has no idea about the original scales (miles and minutes). It only understands the normalized scale it was trained on.
* After the model provides its prediction, you must **de-normalize** the output. This converts the prediction from its normalized scale back into an understandable value in minutes.
* Finally, the code uses this actual predicted time to run the decision logic. For this prediction, assume your company now promises deliveries within 45 minutes and wants to know which vehicle to use. if distance less than 30 meters bike else car

In [ ]:
#distance_to_predict = --------write here

In [ ]:
''''
# Use the torch.no_grad() context manager for efficient prediction
with torch.no_grad():
    # Normalize the input distance
    distance_tensor = torch.tensor([[distance_to_predict]], dtype=torch.float32)
    new_distance_norm = (distance_tensor - distances_mean) / distances_std

    # Get the normalized prediction from the model
    predicted_time_norm = model(new_distance_norm)

    # De-normalize the output to get the actual time in minutes
    predicted_time_actual = (predicted_time_norm * times_std) + times_mean

    # --- Decision Making Logic ---
    print(f"Prediction for a {distance_to_predict}-mile delivery: {predicted_time_actual.item():.1f} minutes")

    # First, check if the delivery is possible within the 45-minute timeframe
    if predicted_time_actual.item() > 45:
        print("\nDecision: Do NOT promise the delivery in under 45 minutes.")
    else:
        # If it is possible, then determine the vehicle based on the distance
        if distance_to_predict <= 3:
            print(f"\nDecision: Yes, delivery is possible. Since the distance is {distance_to_predict} miles (<= 3 miles), use a bike.")
        else:
            print(f"\nDecision: Yes, delivery is possible. Since the distance is {distance_to_predict} miles (> 3 miles), use a car.")

SyntaxError: incomplete input (2301132472.py, line 1)