In [1]:
print("Hello World")

Hello World


In [2]:
# thing on left is assigned value on right, not the other way around
x = 5

In [3]:
print(x)

5


In [ ]:
# other all operators similarly work and equality operators produce 0 1 or true false based on situation, similarly compound conditions
print( (15+20)+(15<25))

36


In [ ]:
# normally number system is decimal, but you can also use binary, octal, and hexadecimal

In [7]:
#normally we use variables to store values to facilitate reuse, but we can also use them to store results of operations, and then use those variables in other operations

In [8]:
# addition of strings is concatenation, and multiplication of strings is repetition
x = "Hello"
y = "World"
print(x + " " + y)

Hello World


In [ ]:
# type of a variable can be checked
x = 15.5
y = type(x)
print(y)

<class 'float'>


In [12]:
# style of print changes on how we use it
type(x)

float

In [14]:
# there is a difference between condition and excecuting something based on condition
print(3>2)  # this is just condtion

if 3>2:
    print("3 is greater than 2")  # this is executing something based on condition

True
3 is greater than 2


In [15]:
# single condition can be checked using if else, but for multiple conditions we use elif
if 70>90:
    print("A")
elif 70>80:
    print("B")
elif 70>70:
    print("C")
elif 70>60:
    print("D")
else:
    print("Equal to 60 which is Fail")

D


In [16]:
# loops are used to repeat a block of code multiple times, and we can use break and continue to control the flow of loops
x = 1
while x < 10:
    print(x)
    x += 1


1
2
3
4
5
6
7
8
9


In [17]:
# for loop auto detects the range of values to iterate over, and we can use break and continue to control the flow of loops
for x in range(1, 10):
    print(x)

1
2
3
4
5
6
7
8
9


In [18]:
# lists are used to store multiple values in a single variable, and we can use indexing to access individual elements of the list
my_list = [1, 2, 3, 4, 5]
print(my_list[0])  # prints 1

1


In [19]:
# full list can be printed using print function, and we can also use slicing to access a range of elements in the list
print(my_list[1:4])  # prints [2, 3, 4]

[2, 3, 4]


In [20]:
# mixing loops and lists, we can iterate over the elements of a list using a for loop
for x in my_list:
    print(x)

1
2
3
4
5


In [ ]:
# lists [], tuples (), sets {}, dictionaries {}, and strings "" are all iterable objects in Python, and we can use loops to iterate over them
# all work roughly the same with different properties that are specific to them

In [22]:
# lists work on index, dictionaries work on keys
# keys cannot be duplicated, but values can be duplicated, and we can use keys to access values in a dictionary
student = {"name": "John", "age": 25, "gender": "male"}
print(student)
print(student["name"])  # prints John

{'name': 'John', 'age': 25, 'gender': 'male'}
John


In [24]:
# if key isn't present it adds that key to the dictionary with the value provided
student["grade"] = "A"
print(student)

{'name': 'John', 'age': 25, 'gender': 'male', 'grade': 'A'}


In [26]:
# length of dictionary can be checked using len function
print(len(student))

4


In [27]:
# traversing a dictionary can be done using for loop, and we can use keys() and values() methods to get the keys and values of the dictionary respectively
for key in student.keys():
    print(key)
    print(student[key])

name
John
age
25
gender
male
grade
A


In [ ]:
# dict values is a datatype that can be converted to list, and we can use list() function to convert it to a list
# it is normally created when we use .values() method on a dictionary, and it is a view object that displays a list of all the values in the dictionary
values = student.values()
print(values)
type(values)

dict_values(['John', 25, 'male', 'A'])


dict_values

In [30]:
# functions
def my_function():
    print("Hello from a function")
my_function()

Hello from a function


In [31]:
# functions with parameters
def my_function_with_parameters(name, age):
    print("Hello " + name + ", you are " + str(age) + " years old")
my_function_with_parameters("John", 25)

Hello John, you are 25 years old


In [32]:
# functions that return values can be used to return a value from a function, and we can use the return statement to return a value from a function
def my_function_with_return(name, age):
    return "Hello " + name + ", you are " + str(age) + " years old"
result = my_function_with_return("John", 25)
print(result)

Hello John, you are 25 years old


In [33]:
# functions with collections
# python can return lists, tuples, sets, and dictionaries from functions, and we can use the return statement to return a collection from a function
def my_function_with_collection():
    return [1, 2, 3, 4, 5]

result = my_function_with_collection()
print(result)

[1, 2, 3, 4, 5]


In [34]:
# recursion is a process in which a function calls itself directly or indirectly, and the corresponding function is called a recursive function, and we can use recursion to solve problems that can be broken down into smaller subproblems
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

result = factorial(5)
print(result)  # prints 120

120


In [1]:
# module importing different ways
from math import sqrt # imports specific function from a module
from math import * # imports all functions from a module
import math # imports the entire module, and we can use the module name to access the functions in the module
import math as m # imports the entire module and gives it an alias, and we can use the alias to access the functions in the module
# you can also import functions and import other python files in the same directory, and we can use the import statement to import a module or a function from a module

In [5]:
# file handling

# opening a file
file = open("example.txt", "w")
# r for reading, w for writing, a for appending, and x for creating a new file and r+ for reading and writing, and we can also use b for binary mode and t for text mode, and we can also use the with statement to open a file, and it will automatically close the file after the block of code is executed

# closing a file
file.close()

In [8]:
# writing to a file
file = open("example.txt", "w")
file.write("Hello World")
file.close()

In [9]:
# escaping characters in strings can be done using the backslash \ character, and we can use it to escape special characters in strings, and we can also use it to create new lines and tabs in strings
file = open("example.txt", "w")
file.write("Hello World\nThis is a new line\n\tThis is a tab")
file.close()

In [10]:
# reading a file
file = open("example.txt", "r")
content = file.read()
print(content)
file.close()

Hello World
This is a new line
	This is a tab


In [11]:
# loops can also be used to read a file line by line, and we can use the readline() method to read a single line from a file, and we can use the readlines() method to read all the lines from a file and return them as a list
file = open("example.txt", "r")
for line in file:
    print(line)
file.close()

Hello World

This is a new line

	This is a tab


In [12]:
# write starts overwriting the file, and append starts adding to the file, and we can use the a mode to append to a file, and we can use the w mode to overwrite a file
file = open("example.txt", "a")
file.write("This is a new line")
file.close()

In [13]:
# type of a file handling variable
type(file)

_io.TextIOWrapper

In [14]:
# readlines
file = open("example.txt", "r")
lines = file.readlines()
print(lines)
file.close()

['Hello World\n', 'This is a new line\n', '\tThis is a tabThis is a new line']


In [15]:
# writelines
file = open("example.txt", "w")
lines = ["This is line 1\n", "This is line 2\n", "This is line 3\n"]
file.writelines(lines)
file.close()

In [16]:
# with statement can be used to open a file, and it will automatically close the file after the block of code is executed, and we can use the with statement to open a file, and it will automatically close the file after the block of code is executed
with open("example.txt", "r") as file:
    content = file.read()
    print(content)

This is line 1
This is line 2
This is line 3



In [19]:
# writing multiple informations in a file
students = ["John", "Jane", "Jim", "Jill"]
marks = [90, 80, 70, 60]
with open("example.txt", "w") as file:
    for i in range(len(students)):
        file.write(students[i] + "," + str(marks[i]) + "\n")


In [ ]:
# useing split and strip
with open("example.txt", "r") as file:
    for line in file:
        student, mark = line.strip().split(",")
        print("Student: " + student + ", Mark: " + mark)


Student: John, Mark: 90
Student: Jane, Mark: 80
Student: Jim, Mark: 70
Student: Jill, Mark: 60


In [21]:
# numpy
import numpy as np

In [22]:
# array converts a list into a numpy array, and we can use the array() function to convert a list into a numpy array
num_list = [1, 2, 3, 4, 5]
num_array = np.array(num_list)
print(num_array)
type(num_array)

[1 2 3 4 5]


numpy.ndarray

In [23]:
# accessing elements of a numpy array can be done using indexing, and we can use slicing to access a range of elements in a numpy array
print(num_array[0])  # access the first element
print(num_array[-1])  # access the last element

1
5


In [24]:
# changing values in a numpy array is similar to changing values in a list, and we can use indexing to change the value of an element in a numpy array, and we can use slicing to change the values of a range of elements in a numpy array
num_array[0] = 10  # change the first element
print(num_array)
num_array[1:4] = [20, 30, 40]  # change a range of elements
print(num_array)

[10  2  3  4  5]
[10 20 30 40  5]


In [25]:
# shape of a numpy array can be checked using the shape attribute, and we can use the reshape() method to change the shape of a numpy array
print(num_array.shape)


(5,)


In [27]:
# data type of a numpy array can be checked using the dtype attribute, and we can use the astype() method to change the data type of a numpy array
print(num_array.dtype)

int64


In [28]:
# size of a numpy array can be checked using the size attribute, and we can use the reshape() method to change the shape of a numpy array
print(num_array.size)

5


In [29]:
# dimensions of a numpy array can be checked using the ndim attribute, and we can use the reshape() method to change the shape of a numpy array
print(num_array.ndim)

1


In [30]:
# different functions to create arrays in numpy include arange(), linspace(), zeros(), ones(), and random.rand(), and we can use these functions to create arrays of different shapes and sizes among others

In [31]:
# alot of list functions starting with a then followed by same name perform same operations on numpy arrays as they do on lists 

In [32]:
# to make a copy of a numpy array, we can use the copy() method, and we can use the view() method to create a view of a numpy array, otherwise 
new_array = num_array.copy()
new_array[0] = 100
print(num_array)  # original array remains unchanged
print(new_array)  # new array has the changed value

[10 20 30 40  5]
[100  20  30  40   5]


In [33]:
# slicing and boolean indexing
num_array = np.array([1, 2, 3, 4, 5])
# slicing
print(num_array[1:4])  # prints [2 3 4]
# boolean indexing
print(num_array[num_array > 2])  # prints [3 4 5]

[2 3 4]
[3 4 5]


In [34]:
# step slicing
print(num_array[::2])  # prints [1 3 5]

[1 3 5]


In [35]:
# two dimensional slicing
num_array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(num_array_2d[1:3, 1:3])  # prints [[5 6] [8 9]]

[[5 6]
 [8 9]]


In [36]:
# three dimensional slicing
num_array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(num_array_3d[1, :, :])  # prints [[5 6] [7 8]]

[[5 6]
 [7 8]]


In [37]:
# fancy indexing
num_array = np.array([1, 2, 3, 4, 5])
indices = [0, 2, 4]
print(num_array[indices])  # prints [1 3 5]

[1 3 5]


In [38]:
# multiple conditions can also be used

In [40]:
# braodcasting is a powerful feature in numpy that allows us to perform operations on arrays of different shapes and sizes, and we can use broadcasting to perform operations on arrays of different shapes and sizes without having to explicitly reshape them
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row = np.array([1, 2, 3])
result = matrix + row  # broadcasting adds the row to each row of the matrix
print(result)  # prints [[ 2  4  6] [ 5  7  9] [ 8 10 12]]

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [41]:
# reshape an array
mat = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_mat = mat.reshape(3, 2)  # reshapes the array to 3 rows and 2 columns
print(reshaped_mat)  # prints [[1 2] [3 4] [5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [42]:
# 0 is column axis and 1 is row axis, and we can use the axis parameter to specify the axis along which to perform an operation, and we can use the sum() method to sum the elements of a numpy array along a specified axis

In [43]:
# pandas
import pandas as pd

In [46]:
# dataframe
students = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 22, 23],
    "Grade": [85, 90, 78]
}
df = pd.DataFrame(students)
print(df)
type(df)

      Name  Age  Grade
0    Alice   20     85
1      Bob   22     90
2  Charlie   23     78


pandas.DataFrame

In [47]:
# info and describe
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str  
 1   Age     3 non-null      int64
 2   Grade   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 219.0 bytes


,Age,Grade
count,3.000000,3.000000
mean,21.666667,84.333333
std,1.527525,6.027714
min,20.000000,78.000000
25%,21.000000,81.500000
50%,22.000000,85.000000
75%,22.500000,87.500000
max,23.000000,90.000000


In [ ]:
# NaN is for values and none is for objects, and we can use the isnull() method to check for NaN values in a dataframe, and we can use the notnull() method to check for non-NaN values in a dataframe